#############################################################################
# Makefile for building: Velasquez.app/Contents/MacOS/Velasquez
# Generated by qmake (2.01a) (Qt 4.5.0) on: ?? ????? 29 12:14:22 2009
# Project:  Velasquez.pro
# Template: app
# Command: /Developer/Qt/bin/qmake -spec /Developer/Qt/mkspecs/macx-xcode -macx -o Velasquez.xcodeproj/project.pbxproj Velasquez.pro
#############################################################################

QMAKE    = /Developer/Qt/bin/qmake
Velasquez.xcodeproj/project.pbxproj: Velasquez.pro  /Developer/Qt/mkspecs/macx-xcode/qmake.conf /Developer/Qt/mkspecs/common/unix.conf \
		/Developer/Qt/mkspecs/common/mac.conf \
		/Developer/Qt/mkspecs/common/mac-g++.conf \
		/Developer/Qt/mkspecs/qconfig.pri \
		/Developer/Qt/mkspecs/features/qt_functions.prf \
		/Developer/Qt/mkspecs/features/qt_config.prf \
		/Developer/Qt/mkspecs/features/exclusive_builds.prf \
		/Developer/Qt/mkspecs/features/default_pre.prf \
		/Developer/Qt/mkspecs/features/mac/default_pre.prf \
		/Developer/Qt/mkspecs/features/release.prf \
		/Developer/Qt/mkspecs/features/default_post.prf \
		/Developer/Qt/mkspecs/features/mac/default_post.prf \
		/Developer/Qt/mkspecs/features/mac/objective_c.prf \
		/Developer/Qt/mkspecs/features/warn_on.prf \
		/Developer/Qt/mkspecs/features/qt.prf \
		/Developer/Qt/mkspecs/features/unix/thread.prf \
		/Developer/Qt/mkspecs/features/moc.prf \
		/Developer/Qt/mkspecs/features/mac/rez.prf \
		/Developer/Qt/mkspecs/features/mac/sdk.prf \
		/Developer/Qt/mkspecs/features/resources.prf \
		/Developer/Qt/mkspecs/features/uic.prf \
		/Developer/Qt/mkspecs/features/yacc.prf \
		/Developer/Qt/mkspecs/features/lex.prf \
		/Developer/Qt/lib/libQtSvg.prl \
		/Developer/Qt/lib/libQtGui.prl \
		/Developer/Qt/lib/libQtCore.prl \
		/Developer/Qt/lib/libQtXml.prl \
		/Developer/Qt/lib/libQtNetwork.prl
	$(QMAKE) -spec /Developer/Qt/mkspecs/macx-xcode -macx -o Velasquez.xcodeproj/project.pbxproj Velasquez.pro
/Developer/Qt/mkspecs/common/unix.conf:
/Developer/Qt/mkspecs/common/mac.conf:
/Developer/Qt/mkspecs/common/mac-g++.conf:
/Developer/Qt/mkspecs/qconfig.pri:
/Developer/Qt/mkspecs/features/qt_functions.prf:
/Developer/Qt/mkspecs/features/qt_config.prf:
/Developer/Qt/mkspecs/features/exclusive_builds.prf:
/Developer/Qt/mkspecs/features/default_pre.prf:
/Developer/Qt/mkspecs/features/mac/default_pre.prf:
/Developer/Qt/mkspecs/features/release.prf:
/Developer/Qt/mkspecs/features/default_post.prf:
/Developer/Qt/mkspecs/features/mac/default_post.prf:
/Developer/Qt/mkspecs/features/mac/objective_c.prf:
/Developer/Qt/mkspecs/features/warn_on.prf:
/Developer/Qt/mkspecs/features/qt.prf:
/Developer/Qt/mkspecs/features/unix/thread.prf:
/Developer/Qt/mkspecs/features/moc.prf:
/Developer/Qt/mkspecs/features/mac/rez.prf:
/Developer/Qt/mkspecs/features/mac/sdk.prf:
/Developer/Qt/mkspecs/features/resources.prf:
/Developer/Qt/mkspecs/features/uic.prf:
/Developer/Qt/mkspecs/features/yacc.prf:
/Developer/Qt/mkspecs/features/lex.prf:
/Developer/Qt/lib/libQtSvg.prl:
/Developer/Qt/lib/libQtGui.prl:
/Developer/Qt/lib/libQtCore.prl:
/Developer/Qt/lib/libQtXml.prl:
/Developer/Qt/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -spec /Developer/Qt/mkspecs/macx-xcode -macx -o Velasquez.xcodeproj/project.pbxproj Velasquez.pro

