description "Gunicorn for risovaska"

start on runlevel [2345]
stop on runlevel [!2345]
kill timeout 5
respawn

env VENV="/srv/.virtualenvs/risovaska"
env LOG="/var/log/risovaska.log"
env PID="/var/run/risovaska.pid"
env SETTINGS="/srv/code/risovaska/settings.py"
env PORT="8020"

script
exec $VENV/bin/gunicorn_django --preload -w 2 --log-level debug --log-file $LOG -p $PID -b 127.0.0.1:$PORT $SETTINGS
end script
