#############################################################################
# Makefile for building: MoodBox.app/Contents/MacOS/MoodBox
# Generated by qmake (2.01a) (Qt 4.5.1) on: Wed Jun 24 20:57:47 2009
# Project:  MoodBox_Mac.pro
# Template: app
# Command: /Developer/Qt/bin/qmake -spec /Developer/Qt/mkspecs/macx-xcode -macx -o MoodBox.xcodeproj/project.pbxproj MoodBox_Mac.pro
#############################################################################

QMAKE    = /Developer/Qt/bin/qmake
MoodBox.xcodeproj/project.pbxproj: MoodBox_Mac.pro  /Developer/Qt/mkspecs/macx-xcode/qmake.conf /Developer/Qt/mkspecs/common/unix.conf \
		/Developer/Qt/mkspecs/common/mac.conf \
		/Developer/Qt/mkspecs/common/mac-g++.conf \
		/Developer/Qt/mkspecs/qconfig.pri \
		/Developer/Qt/mkspecs/features/qt_functions.prf \
		/Developer/Qt/mkspecs/features/qt_config.prf \
		/Developer/Qt/mkspecs/features/exclusive_builds.prf \
		/Developer/Qt/mkspecs/features/default_pre.prf \
		/Developer/Qt/mkspecs/features/mac/default_pre.prf \
		/Developer/Qt/mkspecs/features/release.prf \
		/Developer/Qt/mkspecs/features/default_post.prf \
		/Developer/Qt/mkspecs/features/mac/default_post.prf \
		/Developer/Qt/mkspecs/features/mac/objective_c.prf \
		/Developer/Qt/mkspecs/features/warn_on.prf \
		/Developer/Qt/mkspecs/features/qt.prf \
		/Developer/Qt/mkspecs/features/unix/thread.prf \
		/Developer/Qt/mkspecs/features/moc.prf \
		/Developer/Qt/mkspecs/features/mac/rez.prf \
		/Developer/Qt/mkspecs/features/mac/sdk.prf \
		/Developer/Qt/mkspecs/features/resources.prf \
		/Developer/Qt/mkspecs/features/uic.prf \
		/Developer/Qt/mkspecs/features/yacc.prf \
		/Developer/Qt/mkspecs/features/lex.prf \
		/Developer/Qt/mkspecs/features/include_source_dir.prf \
		/Developer/Qt/lib/libQtSvg.prl \
		/Developer/Qt/lib/libQtGui.prl \
		/Developer/Qt/lib/libQtCore.prl \
		/Developer/Qt/lib/libQtXml.prl \
		/Developer/Qt/lib/libQtNetwork.prl
	$(QMAKE) -spec /Developer/Qt/mkspecs/macx-xcode -macx -o MoodBox.xcodeproj/project.pbxproj MoodBox_Mac.pro
/Developer/Qt/mkspecs/common/unix.conf:
/Developer/Qt/mkspecs/common/mac.conf:
/Developer/Qt/mkspecs/common/mac-g++.conf:
/Developer/Qt/mkspecs/qconfig.pri:
/Developer/Qt/mkspecs/features/qt_functions.prf:
/Developer/Qt/mkspecs/features/qt_config.prf:
/Developer/Qt/mkspecs/features/exclusive_builds.prf:
/Developer/Qt/mkspecs/features/default_pre.prf:
/Developer/Qt/mkspecs/features/mac/default_pre.prf:
/Developer/Qt/mkspecs/features/release.prf:
/Developer/Qt/mkspecs/features/default_post.prf:
/Developer/Qt/mkspecs/features/mac/default_post.prf:
/Developer/Qt/mkspecs/features/mac/objective_c.prf:
/Developer/Qt/mkspecs/features/warn_on.prf:
/Developer/Qt/mkspecs/features/qt.prf:
/Developer/Qt/mkspecs/features/unix/thread.prf:
/Developer/Qt/mkspecs/features/moc.prf:
/Developer/Qt/mkspecs/features/mac/rez.prf:
/Developer/Qt/mkspecs/features/mac/sdk.prf:
/Developer/Qt/mkspecs/features/resources.prf:
/Developer/Qt/mkspecs/features/uic.prf:
/Developer/Qt/mkspecs/features/yacc.prf:
/Developer/Qt/mkspecs/features/lex.prf:
/Developer/Qt/mkspecs/features/include_source_dir.prf:
/Developer/Qt/lib/libQtSvg.prl:
/Developer/Qt/lib/libQtGui.prl:
/Developer/Qt/lib/libQtCore.prl:
/Developer/Qt/lib/libQtXml.prl:
/Developer/Qt/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -spec /Developer/Qt/mkspecs/macx-xcode -macx -o MoodBox.xcodeproj/project.pbxproj MoodBox_Mac.pro

