#include "moodboxmodel.h"

namespace MoodBox
{

MoodBoxModel::MoodBoxModel() : Model()
{
}

MoodBoxModel::~MoodBoxModel()
{
}

void MoodBoxModel::fill()
{
    addTypeInfo(TypeInfo(1, "envelope"));
    addTypeInfo(TypeInfo(2, "header"));
    addTypeInfo(TypeInfo(3, "fault"));
    addTypeInfo(TypeInfo(22, "server_info"));
    addTypeInfo(TypeInfo(4, "user_account"));
    addTypeInfo(TypeInfo(6, "contact_info"));
    addTypeInfo(TypeInfo(7, "art_message"));
    addTypeInfo(TypeInfo(8, "user_info"));
    addTypeInfo(TypeInfo(5, "user_picture_result"));
    addTypeInfo(TypeInfo(9, "contact_login"));
    addTypeInfo(TypeInfo(10, "published_image"));
    addTypeInfo(TypeInfo(11, "publishing_moodstrip_result"));
    addTypeInfo(TypeInfo(32, "publishing_way"));
    addTypeInfo(TypeInfo(12, "moodstrip_result"));
    addTypeInfo(TypeInfo(13, "moodstrip_item_result"));
    addTypeInfo(TypeInfo(14, "user_search_result"));
    addTypeInfo(TypeInfo(15, "moodstrip_search_result"));
    addTypeInfo(TypeInfo(16, "auth_ticket_result"));
    addTypeInfo(TypeInfo(17, "notification_registration_result"));
    addTypeInfo(TypeInfo(18, "notification_result"));
    addTypeInfo(TypeInfo(19, "notification"));
    addTypeInfo(TypeInfo(20, "authorization"));
    addTypeInfo(TypeInfo(21, "send_message_result"));
    addTypeInfo(TypeInfo(23, "contact_logins_result"));
    addTypeInfo(TypeInfo(30, "published_images_result"));
    addTypeInfo(TypeInfo(25, "channel_result"));
    addTypeInfo(TypeInfo(27, "channel_search_result"));
    addTypeInfo(TypeInfo(29, "channel_message"));
    addTypeInfo(TypeInfo(31, "channel_message_url"));
    addTypeInfo(TypeInfo(32, "command_package"));
    addTypeInfo(TypeInfo(33, "package_union"));
    addTypeInfo(TypeInfo(34, "delete_message_command"));
    addTypeInfo(TypeInfo(10094, "get_server_info_result"));
    addTypeInfo(TypeInfo(10093, "get_server_info"));
    addTypeInfo(TypeInfo(10050, "get_commands_result"));
    addTypeInfo(TypeInfo(10049, "get_commands"));
    addTypeInfo(TypeInfo(10002, "get_auth_ticket_result"));
    addTypeInfo(TypeInfo(10001, "get_auth_ticket"));
    addTypeInfo(TypeInfo(10004, "create_account_result"));
    addTypeInfo(TypeInfo(10003, "create_account"));
    addTypeInfo(TypeInfo(10040, "get_user_info_result"));
    addTypeInfo(TypeInfo(10039, "get_user_info"));
    addTypeInfo(TypeInfo(10098, "get_user_info_by_login_result"));
    addTypeInfo(TypeInfo(10097, "get_user_info_by_login"));
    addTypeInfo(TypeInfo(10074, "get_my_account_result"));
    addTypeInfo(TypeInfo(10073, "get_my_account"));
    addTypeInfo(TypeInfo(10006, "update_account_result"));
    addTypeInfo(TypeInfo(10005, "update_account"));
    addTypeInfo(TypeInfo(10010, "get_user_picture_result"));
    addTypeInfo(TypeInfo(10009, "get_user_picture"));
    addTypeInfo(TypeInfo(10038, "update_password_result"));
    addTypeInfo(TypeInfo(10037, "update_password"));
    addTypeInfo(TypeInfo(10064, "reset_password_result"));
    addTypeInfo(TypeInfo(10063, "reset_password"));
    addTypeInfo(TypeInfo(10012, "get_contacts_result"));
    addTypeInfo(TypeInfo(10011, "get_contacts"));
    addTypeInfo(TypeInfo(10082, "get_contact_result"));
    addTypeInfo(TypeInfo(10081, "get_contact"));
    addTypeInfo(TypeInfo(10084, "get_status_result"));
    addTypeInfo(TypeInfo(10083, "get_status"));
    addTypeInfo(TypeInfo(10086, "get_authorization_result"));
    addTypeInfo(TypeInfo(10085, "get_authorization"));
    addTypeInfo(TypeInfo(10016, "process_authorization_request_result"));
    addTypeInfo(TypeInfo(10015, "process_authorization_request"));
    addTypeInfo(TypeInfo(10100, "process_authorization_request_by_login_result"));
    addTypeInfo(TypeInfo(10099, "process_authorization_request_by_login"));
    addTypeInfo(TypeInfo(10018, "process_authorization_response_result"));
    addTypeInfo(TypeInfo(10017, "process_authorization_response"));
    addTypeInfo(TypeInfo(10020, "remove_from_contacts_result"));
    addTypeInfo(TypeInfo(10019, "remove_from_contacts"));
    addTypeInfo(TypeInfo(10030, "block_contact_result"));
    addTypeInfo(TypeInfo(10029, "block_contact"));
    addTypeInfo(TypeInfo(10032, "unblock_contact_result"));
    addTypeInfo(TypeInfo(10031, "unblock_contact"));
    addTypeInfo(TypeInfo(10034, "simple_search_contacts_result"));
    addTypeInfo(TypeInfo(10033, "simple_search_contacts"));
    addTypeInfo(TypeInfo(10036, "advanced_search_contacts_result"));
    addTypeInfo(TypeInfo(10035, "advanced_search_contacts"));
    addTypeInfo(TypeInfo(10022, "send_friend_message_result"));
    addTypeInfo(TypeInfo(10021, "send_friend_message"));
    addTypeInfo(TypeInfo(10024, "send_private_message_result"));
    addTypeInfo(TypeInfo(10023, "send_private_message"));
    addTypeInfo(TypeInfo(10114, "get_next_artmessage_and_report_result"));
    addTypeInfo(TypeInfo(10113, "get_next_artmessage_and_report"));
    addTypeInfo(TypeInfo(10046, "create_moodstrip_result"));
    addTypeInfo(TypeInfo(10045, "create_moodstrip"));
    addTypeInfo(TypeInfo(10072, "add_picture_to_moodstrip_result"));
    addTypeInfo(TypeInfo(10071, "add_picture_to_moodstrip"));
    addTypeInfo(TypeInfo(10052, "delete_moodstrip_result"));
    addTypeInfo(TypeInfo(10051, "delete_moodstrip"));
    addTypeInfo(TypeInfo(10076, "notification_register_result"));
    addTypeInfo(TypeInfo(10075, "notification_register"));
    addTypeInfo(TypeInfo(10078, "notification_unregister_result"));
    addTypeInfo(TypeInfo(10077, "notification_unregister"));
    addTypeInfo(TypeInfo(10080, "get_notifications_result"));
    addTypeInfo(TypeInfo(10079, "get_notifications"));
    addTypeInfo(TypeInfo(10090, "get_notification_timeout_result"));
    addTypeInfo(TypeInfo(10089, "get_notification_timeout"));
    addTypeInfo(TypeInfo(10102, "search_channel_result"));
    addTypeInfo(TypeInfo(10101, "search_channel"));
    addTypeInfo(TypeInfo(10104, "get_channel_info_result"));
    addTypeInfo(TypeInfo(10103, "get_channel_info"));
    addTypeInfo(TypeInfo(10106, "send_channel_message_result"));
    addTypeInfo(TypeInfo(10105, "send_channel_message"));
    addTypeInfo(TypeInfo(10108, "get_next_channel_message_result"));
    addTypeInfo(TypeInfo(10107, "get_next_channel_message"));
    addTypeInfo(TypeInfo(10008, "get_next_channel_message_url_result"));
    addTypeInfo(TypeInfo(10007, "get_next_channel_message_url"));
    addTypeInfo(TypeInfo(10110, "add_user_to_channel_result"));
    addTypeInfo(TypeInfo(10109, "add_user_to_channel"));
    addTypeInfo(TypeInfo(10112, "delete_user_from_channel_result"));
    addTypeInfo(TypeInfo(10111, "delete_user_from_channel"));
    addTypeInfo(TypeInfo(10026, "obscene_channel_message_result"));
    addTypeInfo(TypeInfo(10025, "obscene_channel_message"));
    addTypeInfo(TypeInfo(10048, "delete_message_result"));
    addTypeInfo(TypeInfo(10047, "delete_message"));
    addTypeInfo(TypeInfo(10092, "check_invitation_result"));
    addTypeInfo(TypeInfo(10091, "check_invitation"));

    addEnumValueInfo(EnumValueInfo(20020, 0, "undefined"));
    addEnumValueInfo(EnumValueInfo(20020, 1, "api"));
    addEnumValueInfo(EnumValueInfo(20020, 2, "desktop_client"));
    addEnumValueInfo(EnumValueInfo(20020, 3, "web_site"));
    addEnumValueInfo(EnumValueInfo(20020, 4, "web_widget"));
    addEnumValueInfo(EnumValueInfo(20020, 5, "mobile_client"));


    addEnumValueInfo(EnumValueInfo(20021, 0, "undefined"));
    addEnumValueInfo(EnumValueInfo(20021, 1, "supported"));
    addEnumValueInfo(EnumValueInfo(20021, 2, "not_supported"));


    addEnumValueInfo(EnumValueInfo(20001, 0, "undefined"));
    addEnumValueInfo(EnumValueInfo(20001, 1, "male"));
    addEnumValueInfo(EnumValueInfo(20001, 2, "female"));


    addEnumValueInfo(EnumValueInfo(20002, 0, "undefined"));
    addEnumValueInfo(EnumValueInfo(20002, 241, "CS"));
    addEnumValueInfo(EnumValueInfo(20002, 240, "ZW"));
    addEnumValueInfo(EnumValueInfo(20002, 239, "ZM"));
    addEnumValueInfo(EnumValueInfo(20002, 238, "YU"));
    addEnumValueInfo(EnumValueInfo(20002, 237, "YE"));
    addEnumValueInfo(EnumValueInfo(20002, 236, "EH"));
    addEnumValueInfo(EnumValueInfo(20002, 235, "WF"));
    addEnumValueInfo(EnumValueInfo(20002, 234, "VI"));
    addEnumValueInfo(EnumValueInfo(20002, 233, "VG"));
    addEnumValueInfo(EnumValueInfo(20002, 232, "VN"));
    addEnumValueInfo(EnumValueInfo(20002, 231, "VE"));
    addEnumValueInfo(EnumValueInfo(20002, 230, "VA"));
    addEnumValueInfo(EnumValueInfo(20002, 229, "VU"));
    addEnumValueInfo(EnumValueInfo(20002, 228, "UZ"));
    addEnumValueInfo(EnumValueInfo(20002, 227, "UY"));
    addEnumValueInfo(EnumValueInfo(20002, 226, "UM"));
    addEnumValueInfo(EnumValueInfo(20002, 225, "US"));
    addEnumValueInfo(EnumValueInfo(20002, 224, "GB"));
    addEnumValueInfo(EnumValueInfo(20002, 223, "AE"));
    addEnumValueInfo(EnumValueInfo(20002, 222, "UA"));
    addEnumValueInfo(EnumValueInfo(20002, 221, "UG"));
    addEnumValueInfo(EnumValueInfo(20002, 220, "TV"));
    addEnumValueInfo(EnumValueInfo(20002, 219, "TC"));
    addEnumValueInfo(EnumValueInfo(20002, 218, "TM"));
    addEnumValueInfo(EnumValueInfo(20002, 217, "TR"));
    addEnumValueInfo(EnumValueInfo(20002, 216, "TN"));
    addEnumValueInfo(EnumValueInfo(20002, 215, "TT"));
    addEnumValueInfo(EnumValueInfo(20002, 214, "TO"));
    addEnumValueInfo(EnumValueInfo(20002, 213, "TK"));
    addEnumValueInfo(EnumValueInfo(20002, 212, "TG"));
    addEnumValueInfo(EnumValueInfo(20002, 211, "TH"));
    addEnumValueInfo(EnumValueInfo(20002, 210, "TZ"));
    addEnumValueInfo(EnumValueInfo(20002, 209, "TJ"));
    addEnumValueInfo(EnumValueInfo(20002, 208, "TW"));
    addEnumValueInfo(EnumValueInfo(20002, 207, "SY"));
    addEnumValueInfo(EnumValueInfo(20002, 206, "CH"));
    addEnumValueInfo(EnumValueInfo(20002, 205, "SE"));
    addEnumValueInfo(EnumValueInfo(20002, 204, "SZ"));
    addEnumValueInfo(EnumValueInfo(20002, 203, "SJ"));
    addEnumValueInfo(EnumValueInfo(20002, 202, "SR"));
    addEnumValueInfo(EnumValueInfo(20002, 201, "SD"));
    addEnumValueInfo(EnumValueInfo(20002, 200, "PM"));
    addEnumValueInfo(EnumValueInfo(20002, 199, "SH"));
    addEnumValueInfo(EnumValueInfo(20002, 198, "LK"));
    addEnumValueInfo(EnumValueInfo(20002, 197, "ES"));
    addEnumValueInfo(EnumValueInfo(20002, 196, "GS"));
    addEnumValueInfo(EnumValueInfo(20002, 195, "ZA"));
    addEnumValueInfo(EnumValueInfo(20002, 194, "SO"));
    addEnumValueInfo(EnumValueInfo(20002, 193, "SB"));
    addEnumValueInfo(EnumValueInfo(20002, 192, "SI"));
    addEnumValueInfo(EnumValueInfo(20002, 191, "SK"));
    addEnumValueInfo(EnumValueInfo(20002, 190, "SG"));
    addEnumValueInfo(EnumValueInfo(20002, 189, "SL"));
    addEnumValueInfo(EnumValueInfo(20002, 188, "SC"));
    addEnumValueInfo(EnumValueInfo(20002, 187, "SN"));
    addEnumValueInfo(EnumValueInfo(20002, 186, "SA"));
    addEnumValueInfo(EnumValueInfo(20002, 185, "ST"));
    addEnumValueInfo(EnumValueInfo(20002, 184, "SM"));
    addEnumValueInfo(EnumValueInfo(20002, 183, "WS"));
    addEnumValueInfo(EnumValueInfo(20002, 182, "VC"));
    addEnumValueInfo(EnumValueInfo(20002, 181, "LC"));
    addEnumValueInfo(EnumValueInfo(20002, 180, "KN"));
    addEnumValueInfo(EnumValueInfo(20002, 179, "RW"));
    addEnumValueInfo(EnumValueInfo(20002, 178, "RU"));
    addEnumValueInfo(EnumValueInfo(20002, 177, "RO"));
    addEnumValueInfo(EnumValueInfo(20002, 176, "RE"));
    addEnumValueInfo(EnumValueInfo(20002, 175, "QA"));
    addEnumValueInfo(EnumValueInfo(20002, 174, "PR"));
    addEnumValueInfo(EnumValueInfo(20002, 173, "PT"));
    addEnumValueInfo(EnumValueInfo(20002, 172, "PL"));
    addEnumValueInfo(EnumValueInfo(20002, 171, "PN"));
    addEnumValueInfo(EnumValueInfo(20002, 170, "PH"));
    addEnumValueInfo(EnumValueInfo(20002, 169, "PE"));
    addEnumValueInfo(EnumValueInfo(20002, 168, "PY"));
    addEnumValueInfo(EnumValueInfo(20002, 167, "PG"));
    addEnumValueInfo(EnumValueInfo(20002, 166, "PA"));
    addEnumValueInfo(EnumValueInfo(20002, 165, "PS"));
    addEnumValueInfo(EnumValueInfo(20002, 164, "PW"));
    addEnumValueInfo(EnumValueInfo(20002, 163, "PK"));
    addEnumValueInfo(EnumValueInfo(20002, 162, "OM"));
    addEnumValueInfo(EnumValueInfo(20002, 161, "NO"));
    addEnumValueInfo(EnumValueInfo(20002, 160, "MP"));
    addEnumValueInfo(EnumValueInfo(20002, 159, "NF"));
    addEnumValueInfo(EnumValueInfo(20002, 158, "NU"));
    addEnumValueInfo(EnumValueInfo(20002, 157, "NG"));
    addEnumValueInfo(EnumValueInfo(20002, 156, "NE"));
    addEnumValueInfo(EnumValueInfo(20002, 155, "NI"));
    addEnumValueInfo(EnumValueInfo(20002, 154, "NZ"));
    addEnumValueInfo(EnumValueInfo(20002, 153, "NC"));
    addEnumValueInfo(EnumValueInfo(20002, 152, "AN"));
    addEnumValueInfo(EnumValueInfo(20002, 151, "NL"));
    addEnumValueInfo(EnumValueInfo(20002, 150, "NP"));
    addEnumValueInfo(EnumValueInfo(20002, 149, "NR"));
    addEnumValueInfo(EnumValueInfo(20002, 148, "NA"));
    addEnumValueInfo(EnumValueInfo(20002, 147, "MM"));
    addEnumValueInfo(EnumValueInfo(20002, 146, "MZ"));
    addEnumValueInfo(EnumValueInfo(20002, 145, "MA"));
    addEnumValueInfo(EnumValueInfo(20002, 144, "MS"));
    addEnumValueInfo(EnumValueInfo(20002, 143, "MN"));
    addEnumValueInfo(EnumValueInfo(20002, 142, "MC"));
    addEnumValueInfo(EnumValueInfo(20002, 141, "MD"));
    addEnumValueInfo(EnumValueInfo(20002, 140, "FM"));
    addEnumValueInfo(EnumValueInfo(20002, 139, "MX"));
    addEnumValueInfo(EnumValueInfo(20002, 138, "YT"));
    addEnumValueInfo(EnumValueInfo(20002, 137, "MU"));
    addEnumValueInfo(EnumValueInfo(20002, 136, "MR"));
    addEnumValueInfo(EnumValueInfo(20002, 135, "MQ"));
    addEnumValueInfo(EnumValueInfo(20002, 134, "MH"));
    addEnumValueInfo(EnumValueInfo(20002, 133, "MT"));
    addEnumValueInfo(EnumValueInfo(20002, 132, "ML"));
    addEnumValueInfo(EnumValueInfo(20002, 131, "MV"));
    addEnumValueInfo(EnumValueInfo(20002, 130, "MY"));
    addEnumValueInfo(EnumValueInfo(20002, 129, "MW"));
    addEnumValueInfo(EnumValueInfo(20002, 128, "MG"));
    addEnumValueInfo(EnumValueInfo(20002, 127, "MK"));
    addEnumValueInfo(EnumValueInfo(20002, 126, "MO"));
    addEnumValueInfo(EnumValueInfo(20002, 125, "LU"));
    addEnumValueInfo(EnumValueInfo(20002, 124, "LT"));
    addEnumValueInfo(EnumValueInfo(20002, 123, "LI"));
    addEnumValueInfo(EnumValueInfo(20002, 122, "LY"));
    addEnumValueInfo(EnumValueInfo(20002, 121, "LR"));
    addEnumValueInfo(EnumValueInfo(20002, 120, "LS"));
    addEnumValueInfo(EnumValueInfo(20002, 119, "LB"));
    addEnumValueInfo(EnumValueInfo(20002, 118, "LV"));
    addEnumValueInfo(EnumValueInfo(20002, 117, "LA"));
    addEnumValueInfo(EnumValueInfo(20002, 116, "KG"));
    addEnumValueInfo(EnumValueInfo(20002, 115, "KW"));
    addEnumValueInfo(EnumValueInfo(20002, 114, "KR"));
    addEnumValueInfo(EnumValueInfo(20002, 113, "KP"));
    addEnumValueInfo(EnumValueInfo(20002, 112, "KI"));
    addEnumValueInfo(EnumValueInfo(20002, 111, "KE"));
    addEnumValueInfo(EnumValueInfo(20002, 110, "KZ"));
    addEnumValueInfo(EnumValueInfo(20002, 109, "JO"));
    addEnumValueInfo(EnumValueInfo(20002, 108, "JP"));
    addEnumValueInfo(EnumValueInfo(20002, 107, "JM"));
    addEnumValueInfo(EnumValueInfo(20002, 106, "IT"));
    addEnumValueInfo(EnumValueInfo(20002, 105, "IL"));
    addEnumValueInfo(EnumValueInfo(20002, 104, "IE"));
    addEnumValueInfo(EnumValueInfo(20002, 103, "IQ"));
    addEnumValueInfo(EnumValueInfo(20002, 102, "IR"));
    addEnumValueInfo(EnumValueInfo(20002, 101, "ID"));
    addEnumValueInfo(EnumValueInfo(20002, 100, "IN"));
    addEnumValueInfo(EnumValueInfo(20002, 99, "IS"));
    addEnumValueInfo(EnumValueInfo(20002, 98, "HU"));
    addEnumValueInfo(EnumValueInfo(20002, 97, "HK"));
    addEnumValueInfo(EnumValueInfo(20002, 96, "HN"));
    addEnumValueInfo(EnumValueInfo(20002, 95, "HM"));
    addEnumValueInfo(EnumValueInfo(20002, 94, "HT"));
    addEnumValueInfo(EnumValueInfo(20002, 93, "GY"));
    addEnumValueInfo(EnumValueInfo(20002, 92, "GW"));
    addEnumValueInfo(EnumValueInfo(20002, 91, "GN"));
    addEnumValueInfo(EnumValueInfo(20002, 90, "GT"));
    addEnumValueInfo(EnumValueInfo(20002, 89, "GU"));
    addEnumValueInfo(EnumValueInfo(20002, 88, "GP"));
    addEnumValueInfo(EnumValueInfo(20002, 87, "GD"));
    addEnumValueInfo(EnumValueInfo(20002, 86, "GL"));
    addEnumValueInfo(EnumValueInfo(20002, 85, "GR"));
    addEnumValueInfo(EnumValueInfo(20002, 84, "GI"));
    addEnumValueInfo(EnumValueInfo(20002, 83, "GH"));
    addEnumValueInfo(EnumValueInfo(20002, 82, "DE"));
    addEnumValueInfo(EnumValueInfo(20002, 81, "GE"));
    addEnumValueInfo(EnumValueInfo(20002, 80, "GM"));
    addEnumValueInfo(EnumValueInfo(20002, 79, "GA"));
    addEnumValueInfo(EnumValueInfo(20002, 78, "TF"));
    addEnumValueInfo(EnumValueInfo(20002, 77, "PF"));
    addEnumValueInfo(EnumValueInfo(20002, 76, "GF"));
    addEnumValueInfo(EnumValueInfo(20002, 75, "FX"));
    addEnumValueInfo(EnumValueInfo(20002, 74, "FR"));
    addEnumValueInfo(EnumValueInfo(20002, 73, "FI"));
    addEnumValueInfo(EnumValueInfo(20002, 72, "FJ"));
    addEnumValueInfo(EnumValueInfo(20002, 71, "FO"));
    addEnumValueInfo(EnumValueInfo(20002, 70, "FK"));
    addEnumValueInfo(EnumValueInfo(20002, 69, "ET"));
    addEnumValueInfo(EnumValueInfo(20002, 68, "EE"));
    addEnumValueInfo(EnumValueInfo(20002, 67, "ER"));
    addEnumValueInfo(EnumValueInfo(20002, 66, "GQ"));
    addEnumValueInfo(EnumValueInfo(20002, 65, "SV"));
    addEnumValueInfo(EnumValueInfo(20002, 64, "EG"));
    addEnumValueInfo(EnumValueInfo(20002, 63, "EC"));
    addEnumValueInfo(EnumValueInfo(20002, 62, "TL"));
    addEnumValueInfo(EnumValueInfo(20002, 61, "DO"));
    addEnumValueInfo(EnumValueInfo(20002, 60, "DM"));
    addEnumValueInfo(EnumValueInfo(20002, 59, "DJ"));
    addEnumValueInfo(EnumValueInfo(20002, 58, "DK"));
    addEnumValueInfo(EnumValueInfo(20002, 57, "CZ"));
    addEnumValueInfo(EnumValueInfo(20002, 56, "CY"));
    addEnumValueInfo(EnumValueInfo(20002, 55, "CU"));
    addEnumValueInfo(EnumValueInfo(20002, 54, "HR"));
    addEnumValueInfo(EnumValueInfo(20002, 53, "CI"));
    addEnumValueInfo(EnumValueInfo(20002, 52, "CR"));
    addEnumValueInfo(EnumValueInfo(20002, 51, "CK"));
    addEnumValueInfo(EnumValueInfo(20002, 50, "CG"));
    addEnumValueInfo(EnumValueInfo(20002, 49, "CD"));
    addEnumValueInfo(EnumValueInfo(20002, 48, "KM"));
    addEnumValueInfo(EnumValueInfo(20002, 47, "CO"));
    addEnumValueInfo(EnumValueInfo(20002, 46, "CC"));
    addEnumValueInfo(EnumValueInfo(20002, 45, "CX"));
    addEnumValueInfo(EnumValueInfo(20002, 44, "CN"));
    addEnumValueInfo(EnumValueInfo(20002, 43, "CL"));
    addEnumValueInfo(EnumValueInfo(20002, 42, "TD"));
    addEnumValueInfo(EnumValueInfo(20002, 41, "CF"));
    addEnumValueInfo(EnumValueInfo(20002, 40, "KY"));
    addEnumValueInfo(EnumValueInfo(20002, 39, "CV"));
    addEnumValueInfo(EnumValueInfo(20002, 38, "CA"));
    addEnumValueInfo(EnumValueInfo(20002, 37, "CM"));
    addEnumValueInfo(EnumValueInfo(20002, 36, "KH"));
    addEnumValueInfo(EnumValueInfo(20002, 35, "BI"));
    addEnumValueInfo(EnumValueInfo(20002, 34, "BF"));
    addEnumValueInfo(EnumValueInfo(20002, 33, "BG"));
    addEnumValueInfo(EnumValueInfo(20002, 32, "BN"));
    addEnumValueInfo(EnumValueInfo(20002, 31, "IO"));
    addEnumValueInfo(EnumValueInfo(20002, 30, "BR"));
    addEnumValueInfo(EnumValueInfo(20002, 29, "BV"));
    addEnumValueInfo(EnumValueInfo(20002, 28, "BW"));
    addEnumValueInfo(EnumValueInfo(20002, 27, "BA"));
    addEnumValueInfo(EnumValueInfo(20002, 26, "BO"));
    addEnumValueInfo(EnumValueInfo(20002, 25, "BT"));
    addEnumValueInfo(EnumValueInfo(20002, 24, "BM"));
    addEnumValueInfo(EnumValueInfo(20002, 23, "BJ"));
    addEnumValueInfo(EnumValueInfo(20002, 22, "BZ"));
    addEnumValueInfo(EnumValueInfo(20002, 21, "BE"));
    addEnumValueInfo(EnumValueInfo(20002, 20, "BY"));
    addEnumValueInfo(EnumValueInfo(20002, 19, "BB"));
    addEnumValueInfo(EnumValueInfo(20002, 18, "BD"));
    addEnumValueInfo(EnumValueInfo(20002, 17, "BH"));
    addEnumValueInfo(EnumValueInfo(20002, 16, "BS"));
    addEnumValueInfo(EnumValueInfo(20002, 15, "AZ"));
    addEnumValueInfo(EnumValueInfo(20002, 14, "AT"));
    addEnumValueInfo(EnumValueInfo(20002, 13, "AU"));
    addEnumValueInfo(EnumValueInfo(20002, 12, "AW"));
    addEnumValueInfo(EnumValueInfo(20002, 11, "AM"));
    addEnumValueInfo(EnumValueInfo(20002, 10, "AR"));
    addEnumValueInfo(EnumValueInfo(20002, 9, "AG"));
    addEnumValueInfo(EnumValueInfo(20002, 8, "AQ"));
    addEnumValueInfo(EnumValueInfo(20002, 7, "AI"));
    addEnumValueInfo(EnumValueInfo(20002, 6, "AO"));
    addEnumValueInfo(EnumValueInfo(20002, 5, "AD"));
    addEnumValueInfo(EnumValueInfo(20002, 4, "AS"));
    addEnumValueInfo(EnumValueInfo(20002, 3, "DZ"));
    addEnumValueInfo(EnumValueInfo(20002, 2, "AL"));
    addEnumValueInfo(EnumValueInfo(20002, 1, "AF"));


    addEnumValueInfo(EnumValueInfo(20003, 0, "undefined"));
    addEnumValueInfo(EnumValueInfo(20003, 1, "en"));
    addEnumValueInfo(EnumValueInfo(20003, 2, "ru"));


    addEnumValueInfo(EnumValueInfo(20007, 0, "undefined"));
    addEnumValueInfo(EnumValueInfo(20007, 1, "friends"));
    addEnumValueInfo(EnumValueInfo(20007, 2, "private"));
    addEnumValueInfo(EnumValueInfo(20007, 3, "group"));
    addEnumValueInfo(EnumValueInfo(20007, 4, "channel"));


    addEnumValueInfo(EnumValueInfo(20008, 0, "undefined"));
    addEnumValueInfo(EnumValueInfo(20008, 1, "authorized"));
    addEnumValueInfo(EnumValueInfo(20008, 2, "waits_authorization_from_me"));
    addEnumValueInfo(EnumValueInfo(20008, 3, "not_authorized_me"));


    addEnumValueInfo(EnumValueInfo(20012, 0, "undefined"));
    addEnumValueInfo(EnumValueInfo(20012, 1, "today"));
    addEnumValueInfo(EnumValueInfo(20012, 2, "week"));
    addEnumValueInfo(EnumValueInfo(20012, 3, "month"));
    addEnumValueInfo(EnumValueInfo(20012, 10, "all_time"));


    addEnumValueInfo(EnumValueInfo(20013, 0, "undefined"));
    addEnumValueInfo(EnumValueInfo(20013, 1, "most_recent"));


    addEnumValueInfo(EnumValueInfo(20015, 0, "undefined"));
    addEnumValueInfo(EnumValueInfo(20015, 1, "offline"));
    addEnumValueInfo(EnumValueInfo(20015, 2, "online"));
    addEnumValueInfo(EnumValueInfo(20015, 100, "connecting"));


    addEnumValueInfo(EnumValueInfo(20023, 0, "undefined"));
    addEnumValueInfo(EnumValueInfo(20023, 1, "friend"));
    addEnumValueInfo(EnumValueInfo(20023, 2, "channel"));


    addEnumValueInfo(EnumValueInfo(20004, 0, "undefined"));
    addEnumValueInfo(EnumValueInfo(20004, 1, "ok"));


    addEnumValueInfo(EnumValueInfo(20017, 1, "ok"));
    addEnumValueInfo(EnumValueInfo(20017, 2, "invalid_credentials"));
    addEnumValueInfo(EnumValueInfo(20017, 3, "locked_too_many_attempts"));


    addEnumValueInfo(EnumValueInfo(20005, 1, "ok"));
    addEnumValueInfo(EnumValueInfo(20005, 2, "invalid_login"));
    addEnumValueInfo(EnumValueInfo(20005, 3, "login_is_not_available"));
    addEnumValueInfo(EnumValueInfo(20005, 4, "invalid_password"));
    addEnumValueInfo(EnumValueInfo(20005, 5, "invalid_email"));
    addEnumValueInfo(EnumValueInfo(20005, 6, "invalid_invite_code"));
    addEnumValueInfo(EnumValueInfo(20005, 7, "userpic_size_too_big"));
    addEnumValueInfo(EnumValueInfo(20005, 8, "account_not_found"));
    addEnumValueInfo(EnumValueInfo(20005, 9, "age_must_be_13_or_greater"));


    addEnumValueInfo(EnumValueInfo(20010, 1, "ok"));
    addEnumValueInfo(EnumValueInfo(20010, 2, "userpic_size_too_big"));
    addEnumValueInfo(EnumValueInfo(20010, 3, "not_modified"));
    addEnumValueInfo(EnumValueInfo(20010, 4, "not_found"));


    addEnumValueInfo(EnumValueInfo(20006, 1, "ok"));
    addEnumValueInfo(EnumValueInfo(20006, 2, "incorrect_db_data"));
    addEnumValueInfo(EnumValueInfo(20006, 3, "author_has_too_many_contacts"));
    addEnumValueInfo(EnumValueInfo(20006, 4, "recipient_has_too_many_contacts"));
    addEnumValueInfo(EnumValueInfo(20006, 5, "already_authorized"));
    addEnumValueInfo(EnumValueInfo(20006, 6, "not_waiting_for_authorization"));
    addEnumValueInfo(EnumValueInfo(20006, 7, "authorized_by_this_request"));
    addEnumValueInfo(EnumValueInfo(20006, 8, "account_not_found"));


    addEnumValueInfo(EnumValueInfo(20009, 1, "ok"));
    addEnumValueInfo(EnumValueInfo(20009, 2, "contact_not_found"));
    addEnumValueInfo(EnumValueInfo(20009, 3, "not_authorized_me"));
    addEnumValueInfo(EnumValueInfo(20009, 4, "closed_contact"));


    addEnumValueInfo(EnumValueInfo(20011, 1, "ok"));
    addEnumValueInfo(EnumValueInfo(20011, 2, "moodstrip_not_found"));
    addEnumValueInfo(EnumValueInfo(20011, 3, "moodstrip_is_published"));
    addEnumValueInfo(EnumValueInfo(20011, 4, "moodstrip_is_empty"));


    addEnumValueInfo(EnumValueInfo(20014, 0, "undefined"));
    addEnumValueInfo(EnumValueInfo(20014, 1, "ok"));
    addEnumValueInfo(EnumValueInfo(20014, 2, "unsubscribe_error"));


    addEnumValueInfo(EnumValueInfo(20016, 1, "status_changed"));
    addEnumValueInfo(EnumValueInfo(20016, 2, "userpic_changed"));
    addEnumValueInfo(EnumValueInfo(20016, 3, "contact_changed"));
    addEnumValueInfo(EnumValueInfo(20016, 4, "authorization_changed"));
    addEnumValueInfo(EnumValueInfo(20016, 5, "new_message"));
    addEnumValueInfo(EnumValueInfo(20016, 6, "disconnect"));
    addEnumValueInfo(EnumValueInfo(20016, 7, "reload"));
    addEnumValueInfo(EnumValueInfo(20016, 8, "new_channel_message"));
    addEnumValueInfo(EnumValueInfo(20016, 9, "new_command"));


    addEnumValueInfo(EnumValueInfo(20018, 1, "ok"));
    addEnumValueInfo(EnumValueInfo(20018, 2, "message_data_not_found"));


    addEnumValueInfo(EnumValueInfo(20019, 1, "ok"));
    addEnumValueInfo(EnumValueInfo(20019, 2, "invalid_invite_code"));
    addEnumValueInfo(EnumValueInfo(20019, 3, "limit_was_exceeded"));
    addEnumValueInfo(EnumValueInfo(20019, 4, "invalid_email"));


    addEnumValueInfo(EnumValueInfo(20022, 0, "undefined"));
    addEnumValueInfo(EnumValueInfo(20022, 1, "ok"));
    addEnumValueInfo(EnumValueInfo(20022, 2, "empty"));
    addEnumValueInfo(EnumValueInfo(20022, 3, "hidden"));
    addEnumValueInfo(EnumValueInfo(20022, 4, "forbidden"));


    addEnumValueInfo(EnumValueInfo(20025, 0, "undefined"));
    addEnumValueInfo(EnumValueInfo(20025, 1, "ok"));


    addEnumValueInfo(EnumValueInfo(20026, 0, "undefined"));
    addEnumValueInfo(EnumValueInfo(20026, 1, "simple_url"));
    addEnumValueInfo(EnumValueInfo(20026, 2, "embedded_flash"));
    addEnumValueInfo(EnumValueInfo(20026, 3, "lj"));
    addEnumValueInfo(EnumValueInfo(20026, 4, "lj_cut"));


    addEnumValueInfo(EnumValueInfo(20027, 0, "undefined"));
    addEnumValueInfo(EnumValueInfo(20027, 1, "admin"));


    addPropertyInfo(PropertyInfo(1, 1, "header", true, false));
    addPropertyInfo(PropertyInfo(1, 2, "body", false, true));
    addPropertyInfo(PropertyInfo(2, 1, "auth_ticket", false, false));
    addPropertyInfo(PropertyInfo(2, 2, "version_tag", false, false));
    addPropertyInfo(PropertyInfo(2, 3, "version", false, false));
    addPropertyInfo(PropertyInfo(2, 4, "language", false, false));
    addPropertyInfo(PropertyInfo(3, 1, "code", false, false));
    addPropertyInfo(PropertyInfo(3, 2, "description", false, false));
    addPropertyInfo(PropertyInfo(3, 3, "details", false, false));
    addPropertyInfo(PropertyInfo(22, 1, "is_invitation_required", false, false));
    addPropertyInfo(PropertyInfo(22, 2, "max_request_size", false, false));
    addPropertyInfo(PropertyInfo(4, 1, "id", false, false));
    addPropertyInfo(PropertyInfo(4, 2, "login", false, false));
    addPropertyInfo(PropertyInfo(4, 3, "password", false, false));
    addPropertyInfo(PropertyInfo(4, 4, "creation_date", false, false));
    addPropertyInfo(PropertyInfo(4, 5, "motto", false, false));
    addPropertyInfo(PropertyInfo(4, 6, "about_me", false, false));
    addPropertyInfo(PropertyInfo(4, 7, "name", false, false));
    addPropertyInfo(PropertyInfo(4, 8, "country", false, false));
    addPropertyInfo(PropertyInfo(4, 9, "city", false, false));
    addPropertyInfo(PropertyInfo(4, 10, "email", false, false));
    addPropertyInfo(PropertyInfo(4, 11, "sex", false, false));
    addPropertyInfo(PropertyInfo(4, 12, "birth_day", false, false));
    addPropertyInfo(PropertyInfo(4, 13, "language", false, false));
    addPropertyInfo(PropertyInfo(4, 14, "allow_news", false, false));
    addPropertyInfo(PropertyInfo(4, 15, "allow_publishing", false, false));
    addPropertyInfo(PropertyInfo(4, 16, "allow_show_friends", false, false));
    addPropertyInfo(PropertyInfo(4, 17, "userpic_url", false, false));
    addPropertyInfo(PropertyInfo(4, 18, "role", false, false));
    addPropertyInfo(PropertyInfo(4, 19, "moderate_contacts", true, false));
    addPropertyInfo(PropertyInfo(6, 1, "user_id", false, false));
    addPropertyInfo(PropertyInfo(6, 2, "login", false, false));
    addPropertyInfo(PropertyInfo(6, 3, "status", false, false));
    addPropertyInfo(PropertyInfo(6, 4, "motto", false, false));
    addPropertyInfo(PropertyInfo(6, 5, "name", false, false));
    addPropertyInfo(PropertyInfo(6, 6, "birth_day", false, false));
    addPropertyInfo(PropertyInfo(6, 7, "authorization_state", false, false));
    addPropertyInfo(PropertyInfo(6, 8, "message", false, false));
    addPropertyInfo(PropertyInfo(6, 9, "is_blocked", false, false));
    addPropertyInfo(PropertyInfo(6, 10, "type", false, false));
    addPropertyInfo(PropertyInfo(7, 1, "message_id", false, false));
    addPropertyInfo(PropertyInfo(7, 2, "type", false, false));
    addPropertyInfo(PropertyInfo(7, 3, "author_id", false, false));
    addPropertyInfo(PropertyInfo(7, 4, "send_date", false, false));
    addPropertyInfo(PropertyInfo(7, 5, "data", false, false));
    addPropertyInfo(PropertyInfo(7, 6, "result_code", false, false));
    addPropertyInfo(PropertyInfo(7, 7, "metadata", false, false));
    addPropertyInfo(PropertyInfo(7, 8, "url", false, false));
    addPropertyInfo(PropertyInfo(8, 1, "user_id", false, false));
    addPropertyInfo(PropertyInfo(8, 2, "login", false, false));
    addPropertyInfo(PropertyInfo(8, 3, "name", false, false));
    addPropertyInfo(PropertyInfo(8, 4, "creation_date", false, false));
    addPropertyInfo(PropertyInfo(8, 5, "motto", false, false));
    addPropertyInfo(PropertyInfo(8, 6, "about_me", false, false));
    addPropertyInfo(PropertyInfo(8, 7, "country", false, false));
    addPropertyInfo(PropertyInfo(8, 8, "city", false, false));
    addPropertyInfo(PropertyInfo(8, 9, "sex", false, false));
    addPropertyInfo(PropertyInfo(8, 10, "birth_day", false, false));
    addPropertyInfo(PropertyInfo(8, 11, "userpic_url", false, false));
    addPropertyInfo(PropertyInfo(8, 12, "status", false, false));
    addPropertyInfo(PropertyInfo(8, 13, "show_tv", false, false));
    addPropertyInfo(PropertyInfo(5, 1, "result_code", false, false));
    addPropertyInfo(PropertyInfo(5, 2, "user_id", false, false));
    addPropertyInfo(PropertyInfo(5, 3, "last_change_date", false, false));
    addPropertyInfo(PropertyInfo(5, 4, "picture_data", false, false));
    addPropertyInfo(PropertyInfo(9, 1, "contact_id", false, false));
    addPropertyInfo(PropertyInfo(9, 2, "login", false, false));
    addPropertyInfo(PropertyInfo(10, 1, "send_date", false, false));
    addPropertyInfo(PropertyInfo(10, 2, "url", false, false));
    addPropertyInfo(PropertyInfo(10, 3, "author_login", false, false));
    addPropertyInfo(PropertyInfo(11, 1, "result_code", false, false));
    addPropertyInfo(PropertyInfo(11, 2, "urls", true, false));
    addPropertyInfo(PropertyInfo(32, 1, "code", false, false));
    addPropertyInfo(PropertyInfo(32, 2, "url", false, false));
    addPropertyInfo(PropertyInfo(12, 1, "moodstrip_id", false, false));
    addPropertyInfo(PropertyInfo(12, 2, "author_id", false, false));
    addPropertyInfo(PropertyInfo(12, 3, "author_login", false, false));
    addPropertyInfo(PropertyInfo(12, 4, "title", false, false));
    addPropertyInfo(PropertyInfo(12, 5, "send_date", false, false));
    addPropertyInfo(PropertyInfo(12, 6, "url", false, false));
    addPropertyInfo(PropertyInfo(12, 7, "items", true, false));
    addPropertyInfo(PropertyInfo(12, 8, "count", false, false));
    addPropertyInfo(PropertyInfo(13, 1, "url", false, false));
    addPropertyInfo(PropertyInfo(13, 2, "author_login", false, false));
    addPropertyInfo(PropertyInfo(13, 3, "send_date", false, false));
    addPropertyInfo(PropertyInfo(14, 1, "page_number", false, false));
    addPropertyInfo(PropertyInfo(14, 2, "has_more", false, false));
    addPropertyInfo(PropertyInfo(14, 3, "items", true, false));
    addPropertyInfo(PropertyInfo(15, 1, "page_number", false, false));
    addPropertyInfo(PropertyInfo(15, 2, "has_more", false, false));
    addPropertyInfo(PropertyInfo(15, 3, "items", true, false));
    addPropertyInfo(PropertyInfo(16, 1, "auth_ticket", false, false));
    addPropertyInfo(PropertyInfo(16, 2, "user_id", false, false));
    addPropertyInfo(PropertyInfo(16, 3, "lifetime", false, false));
    addPropertyInfo(PropertyInfo(16, 4, "result_code", false, false));
    addPropertyInfo(PropertyInfo(16, 5, "lock_time", false, false));
    addPropertyInfo(PropertyInfo(17, 1, "server", false, false));
    addPropertyInfo(PropertyInfo(17, 2, "key", false, false));
    addPropertyInfo(PropertyInfo(18, 1, "packet_id", false, false));
    addPropertyInfo(PropertyInfo(18, 2, "notifications", true, false));
    addPropertyInfo(PropertyInfo(19, 1, "user_id", false, false));
    addPropertyInfo(PropertyInfo(19, 2, "event", false, false));
    addPropertyInfo(PropertyInfo(20, 1, "state", false, false));
    addPropertyInfo(PropertyInfo(20, 2, "message", false, false));
    addPropertyInfo(PropertyInfo(21, 1, "result_code", false, false));
    addPropertyInfo(PropertyInfo(21, 2, "message_id", false, false));
    addPropertyInfo(PropertyInfo(21, 3, "send_date", false, false));
    addPropertyInfo(PropertyInfo(23, 1, "result_code", false, false));
    addPropertyInfo(PropertyInfo(23, 2, "users", true, false));
    addPropertyInfo(PropertyInfo(23, 3, "channels", true, false));
    addPropertyInfo(PropertyInfo(30, 1, "result_code", false, false));
    addPropertyInfo(PropertyInfo(30, 2, "images", true, false));
    addPropertyInfo(PropertyInfo(25, 1, "channel_id", false, false));
    addPropertyInfo(PropertyInfo(25, 2, "author_id", false, false));
    addPropertyInfo(PropertyInfo(25, 3, "author_login", false, false));
    addPropertyInfo(PropertyInfo(25, 4, "creation_date", false, false));
    addPropertyInfo(PropertyInfo(25, 5, "title", false, false));
    addPropertyInfo(PropertyInfo(25, 6, "short_description", false, false));
    addPropertyInfo(PropertyInfo(25, 7, "full_description", false, false));
    addPropertyInfo(PropertyInfo(25, 8, "user_count", false, false));
    addPropertyInfo(PropertyInfo(25, 9, "logo_url", false, false));
    addPropertyInfo(PropertyInfo(25, 10, "moderators", true, false));
    addPropertyInfo(PropertyInfo(27, 1, "page_number", false, false));
    addPropertyInfo(PropertyInfo(27, 2, "has_more", false, false));
    addPropertyInfo(PropertyInfo(27, 3, "items", true, false));
    addPropertyInfo(PropertyInfo(29, 1, "result_code", false, false));
    addPropertyInfo(PropertyInfo(29, 2, "message_id", false, false));
    addPropertyInfo(PropertyInfo(29, 3, "author_id", false, false));
    addPropertyInfo(PropertyInfo(29, 4, "author_login", false, false));
    addPropertyInfo(PropertyInfo(29, 5, "send_date", false, false));
    addPropertyInfo(PropertyInfo(29, 6, "data", false, false));
    addPropertyInfo(PropertyInfo(29, 7, "metadata", false, false));
    addPropertyInfo(PropertyInfo(31, 1, "result_code", false, false));
    addPropertyInfo(PropertyInfo(31, 2, "message_id", false, false));
    addPropertyInfo(PropertyInfo(31, 3, "author_id", false, false));
    addPropertyInfo(PropertyInfo(31, 4, "author_login", false, false));
    addPropertyInfo(PropertyInfo(31, 5, "send_date", false, false));
    addPropertyInfo(PropertyInfo(31, 6, "url", false, false));
    addPropertyInfo(PropertyInfo(32, 1, "package_id", false, false));
    addPropertyInfo(PropertyInfo(32, 2, "items", true, false));
    addPropertyInfo(PropertyInfo(33, 1, "value", false, true));
    addPropertyInfo(PropertyInfo(34, 1, "contact_id", false, false));
    addPropertyInfo(PropertyInfo(34, 2, "message_id", false, false));
    addPropertyInfo(PropertyInfo(10094, 1, "result", true, false));
    addPropertyInfo(PropertyInfo(10050, 1, "result", true, false));
    addPropertyInfo(PropertyInfo(10049, 1, "previous_package_id", false, false));
    addPropertyInfo(PropertyInfo(10002, 1, "result", true, false));
    addPropertyInfo(PropertyInfo(10001, 1, "login", false, false));
    addPropertyInfo(PropertyInfo(10001, 2, "password", false, false));
    addPropertyInfo(PropertyInfo(10004, 1, "result", false, false));
    addPropertyInfo(PropertyInfo(10003, 1, "user_account", true, false));
    addPropertyInfo(PropertyInfo(10003, 2, "invite_code", false, false));
    addPropertyInfo(PropertyInfo(10040, 1, "result", true, false));
    addPropertyInfo(PropertyInfo(10039, 1, "user_id", false, false));
    addPropertyInfo(PropertyInfo(10098, 1, "result", true, false));
    addPropertyInfo(PropertyInfo(10097, 1, "login", false, false));
    addPropertyInfo(PropertyInfo(10074, 1, "result", true, false));
    addPropertyInfo(PropertyInfo(10006, 1, "result", false, false));
    addPropertyInfo(PropertyInfo(10005, 1, "user_account", true, false));
    addPropertyInfo(PropertyInfo(10005, 2, "has_user_picture", false, false));
    addPropertyInfo(PropertyInfo(10005, 3, "user_picture", false, false));
    addPropertyInfo(PropertyInfo(10005, 4, "content_type", false, false));
    addPropertyInfo(PropertyInfo(10010, 1, "result", true, false));
    addPropertyInfo(PropertyInfo(10009, 1, "user_id", false, false));
    addPropertyInfo(PropertyInfo(10009, 2, "last_changed_date", false, false));
    addPropertyInfo(PropertyInfo(10038, 1, "result", false, false));
    addPropertyInfo(PropertyInfo(10037, 1, "new_password", false, false));
    addPropertyInfo(PropertyInfo(10037, 2, "old_password", false, false));
    addPropertyInfo(PropertyInfo(10064, 1, "result", false, false));
    addPropertyInfo(PropertyInfo(10063, 1, "login", false, false));
    addPropertyInfo(PropertyInfo(10012, 1, "result", true, false));
    addPropertyInfo(PropertyInfo(10082, 1, "result", true, false));
    addPropertyInfo(PropertyInfo(10081, 1, "user_id", false, false));
    addPropertyInfo(PropertyInfo(10084, 1, "result", false, false));
    addPropertyInfo(PropertyInfo(10083, 1, "user_id", false, false));
    addPropertyInfo(PropertyInfo(10086, 1, "result", true, false));
    addPropertyInfo(PropertyInfo(10085, 1, "user_id", false, false));
    addPropertyInfo(PropertyInfo(10016, 1, "result", false, false));
    addPropertyInfo(PropertyInfo(10015, 1, "recipient_id", false, false));
    addPropertyInfo(PropertyInfo(10015, 2, "authorization_message", false, false));
    addPropertyInfo(PropertyInfo(10100, 1, "result", false, false));
    addPropertyInfo(PropertyInfo(10099, 1, "recipient_login", false, false));
    addPropertyInfo(PropertyInfo(10099, 2, "authorization_message", false, false));
    addPropertyInfo(PropertyInfo(10018, 1, "result", false, false));
    addPropertyInfo(PropertyInfo(10017, 1, "recipient_id", false, false));
    addPropertyInfo(PropertyInfo(10017, 2, "is_accepted", false, false));
    addPropertyInfo(PropertyInfo(10020, 1, "result", false, false));
    addPropertyInfo(PropertyInfo(10019, 1, "contact_user_id", false, false));
    addPropertyInfo(PropertyInfo(10030, 1, "result", false, false));
    addPropertyInfo(PropertyInfo(10029, 1, "contact_user_id", false, false));
    addPropertyInfo(PropertyInfo(10032, 1, "result", false, false));
    addPropertyInfo(PropertyInfo(10031, 1, "contact_user_id", false, false));
    addPropertyInfo(PropertyInfo(10034, 1, "result", true, false));
    addPropertyInfo(PropertyInfo(10033, 1, "page_number", false, false));
    addPropertyInfo(PropertyInfo(10033, 2, "records_per_page", false, false));
    addPropertyInfo(PropertyInfo(10033, 3, "value", false, false));
    addPropertyInfo(PropertyInfo(10036, 1, "result", true, false));
    addPropertyInfo(PropertyInfo(10035, 1, "page_number", false, false));
    addPropertyInfo(PropertyInfo(10035, 2, "records_per_page", false, false));
    addPropertyInfo(PropertyInfo(10035, 3, "value", false, false));
    addPropertyInfo(PropertyInfo(10035, 4, "country", false, false));
    addPropertyInfo(PropertyInfo(10035, 5, "city", false, false));
    addPropertyInfo(PropertyInfo(10035, 6, "sex", false, false));
    addPropertyInfo(PropertyInfo(10035, 7, "min_age", false, false));
    addPropertyInfo(PropertyInfo(10035, 8, "max_age", false, false));
    addPropertyInfo(PropertyInfo(10022, 1, "result", true, false));
    addPropertyInfo(PropertyInfo(10021, 1, "is_public", false, false));
    addPropertyInfo(PropertyInfo(10021, 2, "message", false, false));
    addPropertyInfo(PropertyInfo(10021, 3, "metadata", false, false));
    addPropertyInfo(PropertyInfo(10024, 1, "result", true, false));
    addPropertyInfo(PropertyInfo(10023, 1, "recipient_id", false, false));
    addPropertyInfo(PropertyInfo(10023, 2, "message", false, false));
    addPropertyInfo(PropertyInfo(10023, 3, "metadata", false, false));
    addPropertyInfo(PropertyInfo(10114, 1, "result", true, false));
    addPropertyInfo(PropertyInfo(10113, 1, "previous_message_id", false, false));
    addPropertyInfo(PropertyInfo(10046, 1, "result", false, false));
    addPropertyInfo(PropertyInfo(10045, 1, "caption", false, false));
    addPropertyInfo(PropertyInfo(10045, 2, "is_hidden", false, false));
    addPropertyInfo(PropertyInfo(10045, 3, "channel_id", false, false));
    addPropertyInfo(PropertyInfo(10072, 1, "result", true, false));
    addPropertyInfo(PropertyInfo(10071, 1, "moodstrip_id", false, false));
    addPropertyInfo(PropertyInfo(10071, 2, "message_id", false, false));
    addPropertyInfo(PropertyInfo(10071, 3, "author", false, false));
    addPropertyInfo(PropertyInfo(10071, 4, "data", false, false));
    addPropertyInfo(PropertyInfo(10071, 5, "content_type", false, false));
    addPropertyInfo(PropertyInfo(10071, 6, "is_last", false, false));
    addPropertyInfo(PropertyInfo(10052, 1, "result", false, false));
    addPropertyInfo(PropertyInfo(10051, 1, "moodstrip_id", false, false));
    addPropertyInfo(PropertyInfo(10076, 1, "result", true, false));
    addPropertyInfo(PropertyInfo(10078, 1, "result", false, false));
    addPropertyInfo(PropertyInfo(10077, 1, "key", false, false));
    addPropertyInfo(PropertyInfo(10080, 1, "result", true, false));
    addPropertyInfo(PropertyInfo(10079, 1, "key", false, false));
    addPropertyInfo(PropertyInfo(10079, 2, "packet_id", false, false));
    addPropertyInfo(PropertyInfo(10090, 1, "result", false, false));
    addPropertyInfo(PropertyInfo(10102, 1, "result", true, false));
    addPropertyInfo(PropertyInfo(10101, 1, "page_number", false, false));
    addPropertyInfo(PropertyInfo(10101, 2, "records_per_page", false, false));
    addPropertyInfo(PropertyInfo(10101, 3, "value", false, false));
    addPropertyInfo(PropertyInfo(10104, 1, "result", true, false));
    addPropertyInfo(PropertyInfo(10103, 1, "channel_id", false, false));
    addPropertyInfo(PropertyInfo(10106, 1, "result", true, false));
    addPropertyInfo(PropertyInfo(10105, 1, "channel_id", false, false));
    addPropertyInfo(PropertyInfo(10105, 2, "message", false, false));
    addPropertyInfo(PropertyInfo(10105, 3, "metadata", false, false));
    addPropertyInfo(PropertyInfo(10108, 1, "result", true, false));
    addPropertyInfo(PropertyInfo(10107, 1, "channel_id", false, false));
    addPropertyInfo(PropertyInfo(10107, 2, "last_message_id", false, false));
    addPropertyInfo(PropertyInfo(10107, 3, "skip_message", false, false));
    addPropertyInfo(PropertyInfo(10008, 1, "result", true, false));
    addPropertyInfo(PropertyInfo(10007, 1, "channel_id", false, false));
    addPropertyInfo(PropertyInfo(10007, 2, "last_message_id", false, false));
    addPropertyInfo(PropertyInfo(10007, 3, "skip_message", false, false));
    addPropertyInfo(PropertyInfo(10110, 1, "result", false, false));
    addPropertyInfo(PropertyInfo(10109, 1, "channel_id", false, false));
    addPropertyInfo(PropertyInfo(10112, 1, "result", false, false));
    addPropertyInfo(PropertyInfo(10111, 1, "channel_id", false, false));
    addPropertyInfo(PropertyInfo(10026, 1, "result", false, false));
    addPropertyInfo(PropertyInfo(10025, 1, "channel_id", false, false));
    addPropertyInfo(PropertyInfo(10025, 2, "message_id", false, false));
    addPropertyInfo(PropertyInfo(10048, 1, "result", false, false));
    addPropertyInfo(PropertyInfo(10047, 1, "contact_id", false, false));
    addPropertyInfo(PropertyInfo(10047, 2, "message_type", false, false));
    addPropertyInfo(PropertyInfo(10047, 3, "message_id", false, false));
    addPropertyInfo(PropertyInfo(10092, 1, "result", false, false));
    addPropertyInfo(PropertyInfo(10091, 1, "code", false, false));
}

}
