# -*- coding: utf-8 -*-

def get_time_types():
	return [('today', 'Сегодня'),
		('week', 'За неделю'),
		('month', 'За месяц'),
		('all_time', 'Всё время')]
	
def get_sexex():
	return [('undefined', '(не указан)'),
		('male', 'мужской'),
		('female', 'женский')]

def get_ages():
	return [('0-0', '(не указан)'),
		('1-17', '1-17'),
		('18-23', '18-23'),
		('24-30', '24-30'),
		('31-99', '31+')]

def get_countries():
	return [('', '(не указана)'),
		('RU', 'Россия'),
		('UA', 'Украина'),
		('BY', 'Белоруссия'),
		('KZ', 'Казахстан'),
		('AF', 'Afghanistan'),
		('AL', 'Albania'),
		('DZ', 'Algeria'),
		('AS', 'American Samoa'),
		('AD', 'Andorra'),
		('AO', 'Angola'),
		('AI', 'Anguilla'),
		('AQ', 'Antarctica'),
		('AG', 'Antigua And Barbuda'),
		('AR', 'Argentina'),
		('AM', 'Armenia'),
		('AW', 'Aruba'),
		('AU', 'Australia'),
		('AT', 'Austria'),
		('AZ', 'Azerbaijan'),
		('BS', 'Bahamas'),
		('BH', 'Bahrain'),
		('BD', 'Bangladesh'),
		('BB', 'Barbados'),		
		('BE', 'Belgium'),
		('BZ', 'Belize'),
		('BJ', 'Benin'),
		('BM', 'Bermuda'),
		('BT', 'Bhutan'),
		('BO', 'Bolivia'),
		('BA', 'Bosnia And Herzegowina'),
		('BW', 'Botswana'),
		('BV', 'Bouvet Island'),
		('BR', 'Brazil'),
		('IO', 'British Indian Ocean Territory'),
		('BN', 'Brunei Darussalam'),
		('BG', 'Bulgaria'),
		('BF', 'Burkina Faso'),
		('BI', 'Burundi'),
		('KH', 'Cambodia'),
		('CM', 'Cameroon'),
		('CA', 'Canada'),
		('CV', 'Cape Verde'),
		('KY', 'Cayman Islands'),
		('CF', 'Central African Republic'),
		('TD', 'Chad'),
		('CL', 'Chile'),
		('CN', 'China'),
		('CX', 'Christmas Island'),
		('CC', 'Cocos Islands'),
		('CO', 'Colombia'),
		('KM', 'Comoros'),
		('CD', 'Democratic Republic Of Congo'),
		('CG', 'Peoples Republic Of Congo'),
		('CK', 'Cook Islands'),
		('CR', 'Costa Rica'),
		('CI', 'Ivory Coast'),
		('HR', 'Croatia'),
		('CU', 'Cuba'),
		('CY', 'Cyprus'),
		('CZ', 'Czech Republic'),
		('DK', 'Denmark'),
		('DJ', 'Djibouti'),
		('DM', 'Dominica'),
		('DO', 'Dominican Republic'),
		('TL', 'East Timor'),
		('EC', 'Ecuador'),
		('EG', 'Egypt'),
		('SV', 'El Salvador'),
		('GQ', 'Equatorial Guinea'),
		('ER', 'Eritrea'),
		('EE', 'Estonia'),
		('ET', 'Ethiopia'),
		('FK', 'Falkland Islands'),
		('FO', 'Faroe Islands'),
		('FJ', 'Fiji'),
		('FI', 'Finland'),
		('FR', 'France'),
		('FX', 'Metropolitan France'),
		('GF', 'French Guiana'),
		('PF', 'French Polynesia'),
		('TF', 'French Southern Territories'),
		('GA', 'Gabon'),
		('GM', 'Gambia'),
		('GE', 'Georgia'),
		('DE', 'Germany'),
		('GH', 'Ghana'),
		('GI', 'Gibraltar'),
		('GR', 'Greece'),
		('GL', 'Greenland'),
		('GD', 'Grenada'),
		('GP', 'Guadeloupe'),
		('GU', 'Guam'),
		('GT', 'Guatemala'),
		('GN', 'Guinea'),
		('GW', 'Guinea Bissau'),
		('GY', 'Guyana'),
		('HT', 'Haiti'),
		('HM', 'Heard And McDonald Islands'),
		('HN', 'Honduras'),
		('HK', 'HongKong'),
		('HU', 'Hungary'),
		('IS', 'Iceland'),
		('IN', 'India'),
		('ID', 'Indonesia'),
		('IR', 'Iran'),
		('IQ', 'Iraq'),
		('IE', 'Ireland'),
		('IL', 'Israel'),
		('IT', 'Italy'),
		('JM', 'Jamaica'),
		('JP', 'Japan'),
		('JO', 'Jordan'),
		('KE', 'Kenya'),
		('KI', 'Kiribati'),
		('KP', 'Democratic Republic Of Korea'),
		('KR', 'Republic Of Korea'),
		('KW', 'Kuwait'),
		('KG', 'Kyrgyzstan'),
		('LA', 'Lao'),
		('LV', 'Latvia'),
		('LB', 'Lebanon'),
		('LS', 'Lesotho'),
		('LR', 'Liberia'),
		('LY', 'Libyan Arab Jamahiriya'),
		('LI', 'Liechtenstein'),
		('LT', 'Lithuania'),
		('LU', 'Luxembourg'),
		('MO', 'Macau'),
		('MK', 'Macedonia'),
		('MG', 'Madagascar'),
		('MW', 'Malawi'),
		('MY', 'Malaysia'),
		('MV', 'Maldives'),
		('ML', 'Mali'),
		('MT', 'Malta'),
		('MH', 'Marshall Islands'),
		('MQ', 'Martinique'),
		('MR', 'Mauritania'),
		('MU', 'Mauritius'),
		('YT', 'Mayotte'),
		('MX', 'Mexico'),
		('FM', 'Micronesia'),
		('MD', 'Moldova'),
		('MC', 'Monaco'),
		('MN', 'Mongolia'),
		('MS', 'Montserrat'),
		('MA', 'Morocco'),
		('MZ', 'Mozambique'),
		('MM', 'Myanmar'),
		('NA', 'Namibia'),
		('NR', 'Nauru'),
		('NP', 'Nepal'),
		('NL', 'Netherlands'),
		('AN', 'Netherlands Antilles'),
		('NC', 'New Caledonia'),
		('NZ', 'New Zealand'),
		('NI', 'Nicaragua'),
		('NE', 'Niger'),
		('NG', 'Nigeria'),
		('NU', 'Niue'),
		('NF', 'Norfolk Island'),
		('MP', 'Northern Mariana Islands'),
		('NO', 'Norway'),
		('OM', 'Oman'),
		('PK', 'Pakistan'),
		('PW', 'Palau'),
		('PS', 'Palestinian Territory'),
		('PA', 'Panama'),
		('PG', 'Papua New Guinea'),
		('PY', 'Paraguay'),
		('PE', 'Peru'),
		('PH', 'Philippines'),
		('PN', 'Pitcairn'),
		('PL', 'Poland'),
		('PT', 'Portugal'),
		('PR', 'Puerto Rico'),
		('QA', 'Qatar'),
		('RE', 'Reunion'),
		('RO', 'Romania'),
		('RW', 'Rwanda'),
		('KN', 'Saint Kitts And Nevis'),
		('LC', 'St Lucia'),
		('VC', 'St Vincent And The Grenadines'),
		('WS', 'Samoa'),
		('SM', 'San Marino'),
		('ST', 'Sao Tome And Principe'),
		('SA', 'Saudi Arabia'),
		('SN', 'Senegal'),
		('SC', 'Seychelles'),
		('SL', 'SierraLeone'),
		('SG', 'Singapore'),
		('SK', 'Slovakia'),
		('SI', 'Slovenia'),
		('SB', 'Solomon Islands'),
		('SO', 'Somalia'),
		('ZA', 'South Africa'),
		('GS', 'South Georgia And The South Sandwich Islands'),
		('ES', 'Spain'),
		('LK', 'Sri Lanka'),
		('SH', 'St Helena'),
		('PM', 'St Pierre And Miquelon'),
		('SD', 'Sudan'),
		('SR', 'Suriname'),
		('SJ', 'Svalbard And Jan Mayen Islands'),
		('SZ', 'Swaziland'),
		('SE', 'Sweden'),
		('CH', 'Switzerland'),
		('SY', 'Syrian Arab Republic'),
		('TW', 'Taiwan'),
		('TJ', 'Tajikistan'),
		('TZ', 'Tanzania'),
		('TH', 'Thailand'),
		('TG', 'Togo'),
		('TK', 'Tokelau'),
		('TO', 'Tonga'),
		('TT', 'Trinidad And Tobago'),
		('TN', 'Tunisia'),
		('TR', 'Turkey'),
		('TM', 'Turkmenistan'),
		('TC', 'Turks And Caicos Islands'),
		('TV', 'Tuvalu'),
		('UG', 'Uganda'),
		('AE', 'United Arab Emirates'),
		('GB', 'United Kingdom'),
		('US', 'United States'),
		('UM', 'United States Minor Outlying Islands'),
		('UY', 'Uruguay'),
		('UZ', 'Uzbekistan'),
		('VU', 'Vanuatu'),
		('VA', 'Vatican City State'),
		('VE', 'Venezuela'),
		('VN', 'VietNam'),
		('VG', 'British Virgin Islands'),
		('VI', 'US Virgin Islands'),
		('WF', 'Wallis And Futuna Islands'),
		('EH', 'Western Sahara'),
		('YE', 'Yemen'),
		('YU', 'Yugoslavia'),
		('ZM', 'Zambia'),
		('ZW', 'Zimbabwe')]